# Generated by Django 5.2.15 on 2026-07-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_year', models.IntegerField()),
                ('genre', models.CharField(choices=[('SF', 'SF'), ('Comedy', 'Comedy'), ('Action', 'Action'), ('Drama', 'Drama'), ('Horror', 'Horror')], max_length=20)),
                ('rating', models.FloatField()),
                ('running_time', models.IntegerField()),
                ('content', models.TextField()),
                ('director', models.CharField(max_length=50)),
                ('actors', models.CharField(max_length=200)),
            ],
        ),
    ]
